# Generated by Django 4.0.6 on 2022-07-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'verbose_name': 'Our Snack', 'verbose_name_plural': 'Our Snack'},
        ),
    ]
